name: sync-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'CreatiCoding/creco-script'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          rm -rf .git
          rm -rf .github
          rm -rf README
          aws s3 sync . s3://data.creco.today/script --acl public-read
          aws cloudfront create-invalidation --distribution-id E1UA77V5KRISB --paths "/blog/*"
      - name: alert to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
